### PR TITLE
-Added new carousel, changed css to carousal, added title for preview…

### PR DESCRIPTION
**Pull request by Priyesh91**
… purposes, added break points for mobile responsiveness for carousel ONLY, added test images for testing.

### CODE REVIEW

**Comment by JordanMesibov** [comment]
Looks good to me! Emperor!

**Review by JordanMesibov — APPROVED** [review]
Looks Good!

**Comment by CharityQuinn** [comment]
Looks good

**Review by CharityQuinn — APPROVED** [review]
Looks good!

**Pull request merged**
